# SPDX-License-Identifier: MIT

name: Self Hosted Build

run-name: ${{ github.workflow }} for ${{ github.repository }}

# This workflow represents a specific configuration for a
# single MACHINE as a specific design goal. It utilizes a
# reusable workflow found at distro-core.

# Variables and Actions
# secrets.ACTIONS_STEP_DEBUG                Repository
# secrets.AWS_ACCESS_KEY_ID                 Organization, S3 Access Key
# secrets.AWS_SECRET_ACCESS_KEY             Organization, S3 Secret Key
# secrets.AWS_ENDPOINT_URL                  Organization, S3 Endpoint Hostname
# vars.DISTRO                               Organization, Bitbake DISTRO
# vars.DISTRO_CODENAME                      Organization, Bitbake DISTRO_CODENAME
# vars.MACHINE                              Repository, Bitbake MACHINE
# vars.TARGETS                              Organization, Bitbake TARGETS
# vars.EXTRA_PREMIRRORS_HOST                Organization, Bitbake PREMIRRORS:prepend
# vars.EXTRA_SSTATE_MIRRORS_HOST            Organization, Bitbake SSTATE_MIRRORS:prepend

# Self hosted runners have the prerequsite dependency to
# install the host tools dependencies before workflow use.

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Select runner
        type: choice
        default: '["self-hosted","linux","x64"]'
        options:
        - '["self-hosted","linux","x64"]'
        - '["self-hosted","linux","arm64"]'
      flag_dry_run:
        description: >-
          flag --dry-run
        type: boolean
        default: false
      flag_continue:
        description: >-
          flag --continue
        type: boolean
        default: false
      flag_parse_only:
        description: >-
          flag --parse-only
        type: boolean
        default: false
      flag_no_setscene:
        description: >-
          flag --no-setscene
        type: boolean
        default: false
      # cve-check
      EXTRA_USER_CLASSES:
        description: >
          INHERIT:prepend classes
        type: choice
        default: buildstats buildstats-summary
        options:
        - buildstats buildstats-summary
        - cve-check
      delete_removed:
        description: >
          Sync delete removed
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/') }}

# workflow permissions for current repository

permissions:
  actions: write
  attestations: write
  contents: write
  id-token: write

########################################################################

jobs:

  Run:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    timeout-minutes: 1080
    steps:

    # checkout repo for workflow automation.

    - id: checkout
      uses: actions/checkout@v4
      with:
        clean: false
        fetch-depth: 1

    # setup runner.

    - id: runner
      if: vars.DISTRO != '' && vars.MACHINE != ''
      uses: distro-core/distro-core-action-runner@main
      with:
        mnt_dl_dir: /mnt/downloads
        mnt_sstate_dir: /mnt/sstate-cache

    # keep-alive prevents the workflow from being disabled due to any
    # github repository inactivity.

    - id: keepalive
      uses: liskin/gh-workflow-keepalive@v1.2.1

    # contexts reports in the summary log contents of contexts.

    - id: context
      uses: distro-core/distro-core-action-context@main

    # remove the workspace contents; self-hosted runners retain the
    # workspace artifacts between workflow executions. self-hosted
    # runners return name as label in outputs.

    # - id: pre-cleanup
    #   uses: distro-core/distro-core-action-cleanup@main
    #   with:
    #     paths: |
    #       .repo/local_manifests
    #       build/${{ vars.DISTRO }}/*.{log,lock,sock}
    #       build/${{ vars.DISTRO }}/conf/{.*,*}
    #       build/${{ vars.DISTRO }}/${{ vars.MACHINE }}-tmp

    # repo init, sync and manifest; the job creates the workspace
    # contents and the .repo directory that are referenced in later.

    - id: local-manifests
      shell: bash
      run: |
        : repo-local-manifests
        install -d .repo/local_manifests
        cat <<EOF >.repo/local_manifests/local-manifest.xml
        <?xml version="1.0" encoding="UTF-8"?>
        <manifest>
        EOF
        if [[ "${{ vars.DISTRO_CODENAME }}" = "scarthgap" && "${{ vars.MACHINE }}" = "sbc-xavier-nx-devkit" ]] ; then
        cat <<EOF >>.repo/local_manifests/local-manifest.xml
        <extend-project name="meta-tegra" revision="scarthgap-l4t-r35.x" upstream="scarthgap-l4t-r35.x"/>
        EOF
        fi
        cat <<EOF >>.repo/local_manifests/local-manifest.xml
        <extend-project name="workflows-${{ vars.MACHINE }}" groups="default"/>
        EOF
        cat <<EOF >>.repo/local_manifests/local-manifest.xml
        </manifest>
        EOF

    - uses: distro-core/distro-core-action-repo@main
      with:
        MANIFEST_URL: https://github.com/distro-core/distro-manifest.git
        MANIFEST_NAME: distro-head-${{ vars.DISTRO_CODENAME }}.xml
        MANIFEST_REF: main

    # restore caches.

    - id: restore-build-cache
      uses: actions/cache/restore@v4
      with:
        key: build-cache
        path: |
          build/${{ vars.DISTRO }}/cache

    - id: restore-build-downloads
      if: steps.runner.outputs.runner-environment == 'github-hosted'
      uses: actions/cache/restore@v4
      with:
        key: build-downloads
        path: |
          build/${{ vars.DISTRO }}/downloads

    - id: restore-build-sstate
      if: steps.runner.outputs.runner-environment == 'github-hosted'
      uses: actions/cache/restore@v4
      with:
        key: build-sstate
        path: |
          build/${{ vars.DISTRO }}/${{ vars.MACHINE }}-sstate-cache

    # build steps to create artifacts.

    # - id: bitbake-clean
    #   uses: distro-core/distro-core-action-bitbake@main
    #   with:
    #     DISTRO: ${{ vars.DISTRO }}
    #     MACHINE: ${{ vars.MACHINE }}
    #     TARGETS: ''
    #     TARGET_FLAGS: --cmd cleansstate

    # - id: bitbake-sdk
    #   uses: distro-core/distro-core-action-bitbake@main
    #   with:
    #     DISTRO: ${{ vars.DISTRO }}
    #     MACHINE: ${{ vars.MACHINE }}
    #     TARGETS: ${{ vars.TARGETS }}
    #     TARGET_FLAGS: --cmd populate_sdk

    - id: bitbake-targets
      uses: distro-core/distro-core-action-bitbake@main
      with:
        DISTRO: ${{ vars.DISTRO }}
        MACHINE: ${{ vars.MACHINE }}
        TARGETS: webkitgtk webkitgtk3 ${{ vars.TARGETS }}
        TARGETS_FLAGS: ''
        FLAG_DRY_RUN: ${{ inputs.flag_dry_run && inputs.flag_dry_run || false }}
        FLAG_CONTINUE: ${{ inputs.flag_continue && inputs.flag_continue || false }}
        FLAG_PARSE_ONLY: ${{ inputs.flag_parse_only && inputs.flag_parse_only || false }}
        FLAG_NO_SETSCENE: ${{ inputs.flag_no_setscene && inputs.flag_no_setscene || false }}
        EXTRA_USER_CLASSES: ${{ inputs.EXTRA_USER_CLASSES }}
        # replaces inherit own-mirrors
        EXTRA_PREMIRRORS: >-
          ${{ (steps.runner.outputs.runner-environment == 'self-hosted' && steps.runner.outputs.mnt_dl_dir != '') && format('file://{0}', steps.runner.outputs.mnt_dl_dir) || '' }}
          ${{ (vars.EXTRA_PREMIRRORS_HOST != '') && vars.EXTRA_PREMIRRORS_HOST || '' }}
        # sstate-cache is partitioned by MACHINE
        EXTRA_SSTATE_MIRRORS: >-
          ${{ (vars.EXTRA_SSTATE_MIRRORS_HOST != '') && format(vars.EXTRA_SSTATE_MIRRORS_HOST, vars.MACHINE) || '' }}

    # Artifacts attestation

    # - id: attest
    #   uses: actions/attest-build-provenance@v2
    #   with:
    #     subject-checksums: ${{ steps.bitbake-targets.outputs.deploy_dir }}

    # sync artifacts to S3 storage.

    # - id: s3sync-dl-dir
    #   uses: distro-core/distro-core-action-s3sync@main
    #   with:
    #     src_dir: ${{ steps.bitbake-targets.outputs.dl_dir }}
    #     dst_dir: s3://distro-core-downloads
    #     # delete_removed: ${{ inputs.delete_removed }}
    #     AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - id: s3sync-sstate-dir
    #   uses: distro-core/distro-core-action-s3sync@main
    #   with:
    #     src_dir: ${{ steps.bitbake-targets.outputs.sstate_dir }}
    #     dst_dir: s3://distro-core-sstate-cache/${{ vars.MACHINE }}
    #     # delete_removed: ${{ inputs.delete_removed }}
    #     AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # sync shared artifacts to local storage

    - id: rsync-dl-dir
      if: steps.runner.outputs.mnt_dl_dir != ''
      uses: distro-core/distro-core-action-rsync@main
      with:
        src_dir: ${{ steps.bitbake-targets.outputs.dl_dir }}
        dst_dir: ${{ steps.runner.outputs.mnt_dl_dir }}
        # delete_removed: ${{ inputs.delete_removed }}

    - id: rsync-sstate-dir
      if: steps.runner.outputs.mnt_sstate_dir != ''
      uses: distro-core/distro-core-action-rsync@main
      with:
        src_dir: ${{ steps.bitbake-targets.outputs.sstate_dir }}
        dst_dir: ${{ steps.runner.outputs.mnt_sstate_dir }}
        # delete_removed: ${{ inputs.delete_removed }}

    # refresh caches.

    # - id: gh-cli
    #   shell: bash
    #   env:
    #     NO_COLOR: 1
    #     GH_PROMPT_DISABLED: 1
    #     GH_NO_UPDATE_NOTIFIER: 1
    #     GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    #   run: |
    #     : gh cli
    #     # gh run list --json databaseId -q '.[].databaseId' -w codeql --limit 500 |
    #     #   xargs -IID -P 15 echo gh api \
    #     #   "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" \
    #     #   -X DELETE
    #     : cache usage
    #     gh cache list
    #     gh cache delete ${{ steps.restore-build-cache.outputs.cache-primary-key }} || true
    #     gh cache delete ${{ steps.restore-build-downloads.outputs.cache-primary-key }} || true
    #     gh cache delete ${{ steps.restore-build-sstate.outputs.cache-primary-key }} || true

    - id: delete-build-cache
      if: steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.cache != ''
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        : delete-build-cache
        gh cache delete ${{ steps.restore-build-cache.outputs.cache-primary-key }} || true

    - id: save-build-cache
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.cache != ''
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.restore-build-cache.outputs.cache-primary-key }}
        path: |
          ${{ steps.bitbake-targets.outputs.cache }}

    - id: save-build-downloads
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.dl_dir != '' && steps.runner.outputs.runner-environment == 'github-hosted'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.restore-build-downloads.outputs.cache-primary-key }}
        path: |
          ${{ steps.bitbake-targets.outputs.dl_dir }}/*
          !${{ steps.bitbake-targets.outputs.dl_dir }}/git2
          !${{ steps.bitbake-targets.outputs.dl_dir }}/*.done
          !${{ steps.bitbake-targets.outputs.dl_dir }}/*.lock
          !${{ steps.bitbake-targets.outputs.dl_dir }}/*tmp
          !${{ steps.bitbake-targets.outputs.dl_dir }}/tmp*

    - id: save-build-sstate
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.sstate_dir != '' && steps.runner.outputs.runner-environment == 'github-hosted'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.restore-build-sstate.outputs.cache-primary-key }}
        path: |
          ${{ steps.bitbake-targets.outputs.sstate_dir }}
