# SPDX-License-Identifier: MIT

name: GitHub Hosted Build

run-name: ${{ github.workflow }} for ${{ github.repository }}

# This workflow represents a specific configuration for a
# single MACHINE as a specific design goal. It utilizes a
# reusable workflow found at distro-core.

# Secrets
# secrets.ACTIONS_STEP_DEBUG                Repository
# secrets.AWS_ACCESS_KEY_ID                 Organization, S3 Access Key
# secrets.AWS_SECRET_ACCESS_KEY             Organization, S3 Secret Key
# secrets.AWS_ENDPOINT_URL                  Organization, S3 Endpoint Hostname

# Self hosted runners have the prerequsite dependency to
# install the host tools dependencies before workflow use.

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Select runner
        type: choice
        default: linux-amd64
        options:
        - ubuntu-24.04
        - linux-amd64
      flag_dry_run:
        description: >-
          flag --dry-run
        type: boolean
        default: false
      flag_continue:
        description: >-
          flag --continue
        type: boolean
        default: false
      flag_parse_only:
        description: >-
          flag --parse-only
        type: boolean
        default: false
      flag_no_setscene:
        description: >-
          flag --no-setscene
        type: boolean
        default: false
      EXTRA_USER_CLASSES:
        description: >-
          USER_CLASSES:prepend
        type: choice
        default: none
        options:
        - none
        - cve-check

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/') }}

# workflow permissions for current repository

permissions:
  actions: write
  attestations: write
  contents: write
  id-token: write

########################################################################

# DISTRO:
#   required: true
#   description: >-
#     bitbake variable DISTRO
#     https://docs.yoctoproject.org/ref-manual/variables.html#term-DISTRO
# DISTRO_CODENAME:
#   required: true
#   description: >-
#     bitbake variable DISTRO_CODENAME
#     https://docs.yoctoproject.org/ref-manual/variables.html#term-DISTRO_CODENAME
# MACHINE:
#   required: true
#   description: >-
#     bitbake variable MACHINE
#     https://docs.yoctoproject.org/ref-manual/variables.html#term-MACHINE
# TARGETS:
#   required: true
#   description: >-
#     bitbake command line targets_list
# EXTRA_PREMIRRORS:
#   required: false
#   description: >-
#     bitbake variable PREMIRRORS:prepend
#     https://docs.yoctoproject.org/ref-manual/variables.html#term-PREMIRRORS
# EXTRA_SSTATE_MIRRORS:
#   required: false
#   description: >-
#     bitbake variable SSTATE_MIRRORS:prepend
#     https://docs.yoctoproject.org/ref-manual/variables.html#term-SSTATE_MIRRORS

env:
  REPO_MANIFEST_URL: https://github.com/distro-core/distro-manifest.git
  REPO_MANIFEST_NAME: distro-head-scarthgap.xml
  REPO_MANIFEST_REF: main
  REPO_MANIFEST_LOCAL: >-
    <!-- <extend-project name="meta-distro" revision="main" /> -->
    <!-- <extend-project name="workflows-$MACHINE" groups="default"/> -->
    <!-- <extend-project name="meta-tegra" revision="scarthgap-l4t-r35.x" /> -->
  DISTRO: distro-core
  DISTRO_CODENAME: scarthgap
  MACHINE: wsl-arm64
  TARGETS: wsl-image
  MNT_DL_DIR: /mnt/downloads
  MNT_SSTATE_DIR: /mnt/sstate-cache
  # replaces inherit own-mirrors
  EXTRA_PREMIRRORS: >-
    cvs://.*/.* file:///mnt/downloads
    svn://.*/.* file:///mnt/downloads
    git://.*/.* file:///mnt/downloads
    gitsm://.*/.* file:///mnt/downloads
    bzr://.*/.*  file:///mnt/downloads
    p4://.*/.* file:///mnt/downloads
    osc://.*/.* file:///mnt/downloads
    https?://.*/.* file:///mnt/downloads
    ftp://.*/.* file:///mnt/downloads
    npm://.*/?.* file:///mnt/downloads
    s3://.*/.* file:///mnt/downloads
    crate://.*/.* file:///mnt/downloads
    gs://.*/. file:///mnt/downloads
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('cvs://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('svn://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('git://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('gitsm://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('bzr://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('p4://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('osc://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('https?://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('ftp://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('npm://.*/?.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('s3://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('crate://.*/.* {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
    ${{ secrets.BITBAKE_PREMIRROR_URL && format('gs://.*/. {0}', secrets.BITBAKE_PREMIRROR_URL) || '' }}
  EXTRA_SSTATE_MIRRORS: >-
    file://.* file:///mnt/sstate-cache/PATH
    ${{ secrets.BITBAKE_SSTATE_MIRROR_URL && format('file://.* {0}/PATH', secrets.BITBAKE_SSTATE_MIRROR_URL) || '' }}

########################################################################

jobs:

  Run:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 1080
    steps:

    # checkout repo for workflow automation.

    - id: checkout
      uses: actions/checkout@v4
      with:
        clean: false
        fetch-depth: 1

    # setup runner.

    - id: runner
      if: env.DISTRO != '' && env.MACHINE != ''
      uses: distro-core/actions/runner@main
      with:
        mnt_dl_dir: ${{ env.MNT_DL_DIR }}
        mnt_sstate_dir: ${{ env.MNT_SSTATE_DIR }}

    # keep-alive prevents the workflow from being disabled due to any
    # github repository inactivity.

    - id: keepalive
      uses: distro-core/actions/keepalive@main

    # contexts reports in the summary log contents of contexts.

    - id: context
      uses: distro-core/actions/context@main

    # remove the workspace contents; self-hosted runners retain the
    # workspace artifacts between workflow executions. self-hosted
    # runners return name as label in outputs.

    # - id: pre-cleanup
    #   uses: distro-core/actions/cleanup@main
    #   with:
    #     paths: |
    #       build/*.{log,lock,sock}
    #       build/conf/{.*,*}
    #       build/tmp

    # repo init, sync and manifest; the job creates the workspace
    # contents and the .repo directory that are referenced in later.
    # environment variables are set for the manifest and the repo.

    - id: repo-manifest
      uses: distro-core/actions/repo@main

    # restore caches.

    - id: restore-build-cache
      uses: actions/cache/restore@v4
      with:
        key: build-cache
        path: |
          build/cache

    - id: restore-build-downloads
      uses: actions/cache/restore@v4
      with:
        key: build-downloads
        path: |
          build/downloads

    - id: restore-build-sstate
      uses: actions/cache/restore@v4
      with:
        key: build-sstate
        path: |
          build/sstate-cache

    # build steps to create artifacts.

    # - id: bitbake-clean
    #   uses: distro-core/actions/bitbake@main
    #   with:
    #     TARGETS: ''
    #     TARGET_FLAGS: --cmd cleansstate

    # - id: bitbake-sdk
    #   uses: distro-core/actions/bitbake@main
    #   with:
    #     TARGETS: ${{ env.TARGETS }}
    #     TARGET_FLAGS: --cmd populate_sdk

    - id: bitbake-targets
      uses: distro-core/actions/bitbake@main
      with:
        TARGETS: ${{ env.TARGETS }}
        TARGETS_FLAGS:
        FLAG_DRY_RUN: ${{ inputs.flag_dry_run && inputs.flag_dry_run || false }}
        FLAG_CONTINUE: ${{ inputs.flag_continue && inputs.flag_continue || false }}
        FLAG_PARSE_ONLY: ${{ inputs.flag_parse_only && inputs.flag_parse_only || false }}
        FLAG_NO_SETSCENE: ${{ inputs.flag_no_setscene && inputs.flag_no_setscene || false }}
        EXTRA_USER_CLASSES: ${{ inputs.EXTRA_USER_CLASSES }}

    # Artifacts attestation

    # - id: attest
    #   uses: actions/attest-build-provenance@v2
    #   with:
    #     subject-checksums: ${{ steps.bitbake-targets.outputs.deploy_dir }}

    # sync artifacts to S3 storage.

    - id: s3cmd-dl-dir
      if: steps.bitbake-targets.outputs.dl_dir != ''
      uses: distro-core/actions/s3cmd@main
      with:
        src_dir: ${{ steps.bitbake-targets.outputs.dl_dir }}
        dst_dir: s3://distro-core-downloads
        AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - id: s3cmd-sstate-dir
      if: steps.bitbake-targets.outputs.sstate_dir != ''
      uses: distro-core/actions/s3cmd@main
      with:
        src_dir: ${{ steps.bitbake-targets.outputs.sstate_dir }}
        dst_dir: s3://distro-core-sstate-cache
        AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # sync shared artifacts to local storage

    - id: rsync-dl-dir
      if: steps.bitbake-targets.outputs.dl_dir != '' && steps.runner.outputs.mnt_dl_dir != ''
      uses: distro-core/actions/rsync@main
      with:
        src_dir: ${{ steps.bitbake-targets.outputs.dl_dir }}
        dst_dir: ${{ steps.runner.outputs.mnt_dl_dir }}

    - id: rsync-sstate-dir
      if: steps.bitbake-targets.outputs.sstate_dir != '' && steps.runner.outputs.mnt_sstate_dir != ''
      uses: distro-core/actions/rsync@main
      with:
        src_dir: ${{ steps.bitbake-targets.outputs.sstate_dir }}
        dst_dir: ${{ steps.runner.outputs.mnt_sstate_dir }}

    # refresh caches.

    # - id: delete-build-cache
    #   if: steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.cache != ''
    #   shell: bash
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     : delete-build-cache
    #     gh cache delete build-cache || true

    - id: save-build-cache
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.cache != ''
      uses: actions/cache/save@v4
      with:
        key: build-cache
        path: |
          ${{ steps.bitbake-targets.outputs.cache }}/*
          !${{ steps.bitbake-targets.outputs.cache }}/bb_cache*
          !${{ steps.bitbake-targets.outputs.cache }}/bb_codeparser*

    - id: remove-build-cache
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.cache != ''
      shell: bash
      run: |
        : remove-build-cache
        rm -fr ${{ steps.bitbake-targets.outputs.cache }}

    # - id: delete-build-downloads
    #   if: steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.dl_dir != ''
    #   shell: bash
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     : delete-build-downloads
    #     gh cache delete build-downloads || true

    - id: save-build-downloads
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.dl_dir != ''
      uses: actions/cache/save@v4
      with:
        key: build-downloads
        path: |
          ${{ steps.bitbake-targets.outputs.dl_dir }}/*
          !${{ steps.bitbake-targets.outputs.dl_dir }}/git2
          !${{ steps.bitbake-targets.outputs.dl_dir }}/*.done
          !${{ steps.bitbake-targets.outputs.dl_dir }}/*.lock
          !${{ steps.bitbake-targets.outputs.dl_dir }}/*tmp
          !${{ steps.bitbake-targets.outputs.dl_dir }}/tmp*

    - id: remove-build-downloads
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.dl_dir != ''
      shell: bash
      run: |
        : remove-build-downloads
        rm -fr ${{ steps.bitbake-targets.outputs.dl_dir }}

    # - id: delete-build-sstate
    #   if: steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.sstate_dir != ''
    #   shell: bash
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     : delete-build-sstate
    #     gh cache delete build-downloads || true

    - id: save-build-sstate
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.sstate_dir != ''
      uses: actions/cache/save@v4
      with:
        key: build-sstate
        path: |
          ${{ steps.bitbake-targets.outputs.sstate_dir }}

    - id: remove-build-sstate
      if: always() && steps.bitbake-targets.conclusion == 'success' && steps.bitbake-targets.outputs.sstate_dir != ''
      shell: bash
      run: |
        : remove-build-sstate
        rm -fr ${{ steps.bitbake-targets.outputs.sstate_dir }}

    # - id: next-workflow
    #   if: steps.bitbake-targets.conclusion == 'success'
    #   shell: bash
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     : next-step
    #     gh workflow run --repo ${{ github.repository }} github-hosted-build-2.yml \
    #       -f runs-on="${{ inputs.runs-on }}" \
    #       -f flag_dry_run="${{ inputs.flag_dry_run }}" \
    #       -f flag_continue="${{ inputs.flag_continue }}" \
    #       -f flag_parse_only="${{ inputs.flag_parse_only }}" \
    #       -f flag_no_setscene="${{ inputs.flag_no_setscene }}" \
    #       -f EXTRA_USER_CLASSES="${{ inputs.EXTRA_USER_CLASSES }}"
